### ISSUE TITLE
Update rules

### ISSUE THREAD

**Issue by alexlepinski** [osu-cass/tslint-config#1]
- no-implicit-dependencies (AboutItem/AboutItem react-router says we don't have it but we do in package.json)
  - [ ] AboutItem/AboutItem `import { Redirect } from "react-router";`
- prefer-method-signature (when we pass clients and arrows down)
  - [ ] Button/BtnGroupOption line 8 `onClick: () => void;`
- react-this-binding-issue (on handlers we use arrow statements. we could move these to anonymous methods but that is overkill in some situations)
  - [ ] ItemTable/ItemTableRow line 116 `e => this.handleCheckboxClick(e, rowData)`

- ALSO:
checkout to see if we want to disable JSDOC tag '@interface' is redundant (it will do this for member properties as well). tslint throws an issue becuase typescript can derive the types but I think we want them. 
  - [ ] Linke 16 ` * @param {BtnGroupOptionProps} props btn props for button group`

**Comment by alexlepinski** [comment]
please checkout http://typedoc.org/guides/doccomments/ for jsdoc.

**Comment by puregarlic** [comment]
I'd like to add that the `prettier` rule appears to be deprecated now, we should remove it to clean up our output logs.
