### ISSUE TITLE
Remove rule enforcing documentation for classes

### ISSUE THREAD

**Issue by danvanhorn** [osu-cass/tslint-config#7]
We don't need this rule because we're not utilizing JSDocs.

**Comment by puregarlic** [comment]
Actually, I think this is going to require a larger conversation. We can disable documentation for exported classes, but there's quite a bit of configuration available in this rule. You can see the documentation here: https://palantir.github.io/tslint/rules/completed-docs/

I think we need to have a discussion about what we want to have documented, if ever. I don't think it's safe to assume that Typescript will save us in all situations.

**Comment by puregarlic** [comment]
Closing this in favor of keeping the rule enabled.
